import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "./components/NavbarWrapper";
import { ThemeProvider } from "./components/ThemeProvider";
import { Toaster } from "sonner";
import { AuthProvider } from "./lib/context/AuthContext";
import { getUser } from "./lib/actions/auth";
import { getThemeFromCookies } from "./lib/theme-server";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  const theme = await getThemeFromCookies();
  
  return (
    <html lang="en" className={theme} suppressHydrationWarning>
      <body className={openSans.className}>
        <AuthProvider initialUser={user}>
          <ThemeProvider initialTheme={theme}>
            <NavbarWrapper />
            <main>{children}</main>
            <Toaster position="top-right" richColors />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
